# Deployment Bucket and Image Bucket
# Ref:https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/quickref-s3.md

AWSTemplateFormatVersion: 2010-09-09

Parameters:
    Prefix:
      Type: String
    Env:
      Type: String
      Default: dev
      AllowedValues:
        - dev
        - production


Resources:
  ServerlessBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join ["-",[!Ref Prefix, !Ref Env, "serverless"]]
      AccessControl: PublicRead
    
  ServerlessImageBucket: 
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join ["-",[!Ref Prefix, !Ref Env, "serverless-image"]]

Outputs:
  ServerlessBucket:
    Value: !Ref ServerlessBucket
    Export:
      Name: !Sub "${AWS::StackName}-ServerlessBucket"
  
  ServerlessImageBucket:
    Value: !Ref ServerlessImageBucket
    Export:
      Name: !Sub "${AWS::StackName}-ServerlessImageBucket"